// Code generated by goctl. DO NOT EDIT.
package types

type FileDownloadRequest struct {
	FileName string
}

type FileDownloadResponse struct {
	Identity string `json:"identity"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}

type FileUploadRequest struct {
	FileName string
	FileData []byte
}

type LoginReply struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type MailCodeSendReply struct {
	Code string `json:"code"`
}

type MailCodeSendRequest struct {
	Email string `json:"email"`
}

type RefreshAuthorizationReply struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type RefreshAuthorizationRequest struct {
}

type UserDetailReply struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserRegisterReply struct {
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}
